# Generated by Django 4.1.6 on 2023-03-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0002_remove_profile_name_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
